name: Terraform Plan

on:
    pull_request:
    push:
        branches:
            - main
permissions:
    id-token: write
    contents: read

jobs:
    terraform-plan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4