name: Terraform Plan

on:
    pull_request:
    push:
        branches:
            - main
permissions:
    id-token: write
    contents: read

concurrency:
  group: terraform-plan-${{github.ref}}-${{matrix.environment}}
  cancel-in-progress: true

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [dev, staging, prod]
      
    environment: ${{format('{0}-plan', matrix.environment)}}

    env:
        TF_VAR_abuseipdb_api_key: ${{secrets.ABUSEIPDB_API_KEY}}
        TF_VAR_bucket_admin_principals: ${{vars.BUCKET_ADMIN_PRINCIPALS}}
        TF_VAR_tf_state_bucket_arn: ${{vars.TF_STATE_BUCKET_ARN}}
        TF_VAR_tf_state_bucket_cmk_arn: ${{vars.TF_STATE_BUCKET_CMK_ARN}}
        TF_VAR_tf_state_lock_table_arn: ${{vars.TF_STATE_LOCK_TABLE_ARN}}
        TF_VAR_break_glass_trusted_principal_arns: ${{vars.BREAK_GLASS_TRUSTED_PRINCIPAL_ARNS}}
        TF_VAR_secops_emails: ${{vars.SECOPS_EMAILS}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials from GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{vars.PLAN_ROLE_GITHUB_ARN}}
          aws-region: ${{vars.PRIMARY_REGION}}

      - name: Verify identity
        run: aws sts get-caller-identity

      - name: Verify S3 access
        run: aws s3 ls s3://tf-secure-baseline-state/tf-state-baseline

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./environments/${{matrix.environment}}
        run: terraform init

      - name: Terraform Validate
        working-directory: ./environments/${{matrix.environment}}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./environments/${{matrix.environment}}
        run: terraform plan -no-color