name: Terraform Plan

on:
    pull_request:
    push:
        branches:
            - main
permissions:
    id-token: write
    contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: dev
            github_environment: dev-plan
            working_directory: ./environments/dev
          - environment: prod
            github_environment: prod-plan
            working_directory: ./environments/prod
          - environment: staging
            github_environment: staging-plan
            working_directory: ./environments/staging
          - environment: control-plane-account
            github_environment: control-plane-plan
            working_directory: ./bootstrap/control_plane/account
          - environment: control-plane-identity-center
            github_environment: control-plane-plan
            working_directory: ./bootstrap/control_plane/identity_center
          - environment: control-plane-organizations
            github_environment: control-plane-plan
            working_directory: ./bootstrap/control_plane/organizations

    concurrency:
      group: terraform-plan-${{github.head_ref || github.ref_name}}-${{matrix.environment}}
      cancel-in-progress: false

    environment: ${{matrix.github_environment}}

    env:
        TF_VAR_abuseipdb_api_key: ${{secrets.ABUSEIPDB_API_KEY}}
        TF_VAR_bucket_admin_principals: ${{vars.BUCKET_ADMIN_PRINCIPALS}}
        TF_VAR_tf_state_bucket_arn: ${{vars.TF_STATE_BUCKET_ARN}}
        TF_VAR_tf_state_bucket_cmk_arn: ${{vars.TF_STATE_BUCKET_CMK_ARN}}
        TF_VAR_tf_state_lock_table_arn: ${{vars.TF_STATE_LOCK_TABLE_ARN}}
        TF_VAR_break_glass_trusted_principal_arns: ${{vars.BREAK_GLASS_TRUSTED_PRINCIPAL_ARNS}}
        TF_VAR_secops_emails: ${{vars.SECOPS_EMAILS}}
        TF_VAR_account_id_dev: ${{vars.ACCOUNT_ID_DEV}}
        TF_VAR_account_id_prod: ${{vars.ACCOUNT_ID_PROD}}
        TF_VAR_account_id_staging: ${{vars.ACCOUNT_ID_STAGING}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials from GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{vars.PLAN_ROLE_GITHUB_ARN}}
          aws-region: ${{vars.PRIMARY_REGION}}

      - name: Verify identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{matrix.working_directory}}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{matrix.working_directory}}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{matrix.working_directory}}
        run: terraform plan -no-color -lock-timeout=5m