name: Terraform Destroy

on:
    workflow_dispatch:
        inputs:
            confirm:
                description: "Type DESTROY to destroy infrastructure"
                required: true

permissions:
    id-token: write
    contents: read

concurrency:
    group: terraform-destroy-dev
    cancel-in-progress: false

jobs:
    terraform-destroy:
        runs-on: ubuntu-latest
        environment: dev

        env:
            TF_VAR_abuseipdb_api_key: ${{secrets.ABUSEIPDB_API_KEY}}
            TF_VAR_bucket_admin_principals: ${{vars.BUCKET_ADMIN_PRINCIPALS}}
            TF_VAR_tf_state_bucket_arn: ${{vars.TF_STATE_BUCKET_ARN}}
            TF_VAR_tf_state_bucket_cmk_arn: ${{vars.TF_STATE_BUCKET_CMK_ARN}}
            TF_VAR_tf_state_lock_table_arn: ${{vars.TF_STATE_LOCK_TABLE_ARN}}
            TF_VAR_break_glass_trusted_principal_arns: ${{vars.BREAK_GLASS_TRUSTED_PRINCIPAL_ARNS}}
            TF_VAR_secops_emails: ${{vars.SECOPS_EMAILS}}

        steps:
            - name: Confirm destroy
              run: |
                if [ "${{ github.event.inputs.confirm }}" != "DESTROY" ]; then
                    echo "Confirmation failed. Aborting."
                    exit 1
                fi

            - name: Checkout
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::072288671186:role/tf-secure-baseline-dev-github-apply-role
                aws-region: us-east-1

            - name: Verify identity
              run: aws sts get-caller-identity

            - name: Verify S3 access
              run: aws s3 ls s3://tf-secure-baseline-state/tf-state-baseline

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              working-directory: ./baseline
              run: terraform init

            - name: Terraform Destroy
              working-directory: ./baseline
              shell: bash
              run: |
                set -o pipefail
                terraform destroy -auto-approve -input=false -no-color -lock-timeout=5m 2>&1 | tee destroy.log