#####################################################
## GIT WORKFLOW FOR CI/CD PIPELINE TERRAFORM SCANS ##
#####################################################

name: Terraform Static Analysis

on:
  push:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '**/.github/workflows/tf-scans.yml'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '**/.github/workflows/tf-scans.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform_static_analysis:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
      TF_PLUGIN_CACHE_DIR: "/home/runner/.terraform.d/plugin-cache"

    strategy:
      fail-fast: false
      matrix:
        working_directory:
          - environments/dev
          - environmnets/staging
          - environments/prod

          - bootstrap/control_plane/account
          - bootstrap/control_plane/identity_center
          - bootstrap/control_plane/organizations
          - bootstrap/control_plane/state

          - bootstrap/dev/account
          - bootstrap/dev/state

          - bootstrap/staging/account
          - bootstrap/staging/state

          - bootstrap/prod/account
          - bootstrap/prod/state

    defaults:
      run:
        shell: bash
        working-directory: ${{matrix.working_directory}}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

        # CREATE CLEAN EVIDENCE DIRECTORY
      - name: Prepare Report Directory
        run: |
          rm -rf reports
          mkdir -p reports

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.2

      - name: Create Plugin Cache Directory
        run: mkdir -p ~/.terraform.d/plugin-cache

      - name: Terraform Format Check
        working-directory: ${{matrix.working_directory}}
        run: |
          set -o pipefail
          terraform fmt -check -recursive | tee reports/terraform-fmt.txt

      - name: Terraform Init (no backend)
        working-directory: ${{matrix.working_directory}}
        run: |
          set -o pipefail
          terraform init -backend=false -input=false -no-color | tee reports/terraform-init.txt

      - name: Terraform Validate
        working-directory: ${{matrix.working_directory}}
        run: |
          set -o pipefail
          terraform validate -no-color 2>&1 | tee reports/terraform-validate.txt

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v6

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint (compact)
        run: |
          set -o pipefail
          tflint --recursive -f compact 2>&1 | tee reports/tflint-compact.txt || true

      - name: Run TFLint (JUnit)
        run: |
          set -o pipefail
          tflint --recursive -f junit > reports/tflint-junit.xml || true

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov Scan (JUNIT)
        run: |
          set -o pipefail
          checkov -d . -o junitxml --soft-fail > reports/checkov-junit.xml || true

      - name: Run Checkov Scan (JSON)
        run: |
          set -o pipefail
          checkov -d . -o json --soft-fail > reports/checkov.json || true

      - name: Upload Scan Results
        uses: actions/upload-artifact@v6
        with:
            name: ci-evidence
            path: reports/
            if-no-files-found: error